<?php

class PxlMenuList_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_menu_list';
    protected $title = 'Menu Restaurant Pxl';
    protected $icon = 'eicon-gallery-grid';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_layout","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/mrittik\/wp-content\/themes\/mrittik\/elements\/templates\/pxl_menu_list\/img-layout\/layout1.jpg"}}}]},{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"menu_list","label":"Menu List","type":"repeater","default":[],"controls":[{"name":"title","label":"Title","type":"text","label_block":true},{"name":"excerpt","label":"Excerpt","type":"textarea","label_block":true},{"name":"price","label":"Price","type":"text","label_block":true}],"title_field":"{{{ title }}}"},{"name":"active_section","label":"Active section","type":"number","separator":"after"}]},{"name":"section_settings","label":"Grid","tab":"settings","controls":[{"name":"filter","label":"Filter by categories","type":"select","default":"false","options":{"true":"Enable","false":"Disable"}},{"name":"filter_default_title","label":"Default Title","type":"text","default":"All","condition":{"filter":"true"}},{"name":"filter_alignment","label":"Alignment","type":"select","default":"center","options":{"center":"Center","left":"Left","right":"Right"},"condition":{"filter":"true"}}]},{"name":"tab_el_title","label":"Filter Style","tab":"style","controls":[{"name":"filter_color","label":"Filter Color","type":"color","selectors":{"{{WRAPPER}} .grid-filter-wrap .filter-item":"color: {{VALUE}};"}},{"name":"filter_active_color","label":"Filter Active Color","type":"color","selectors":{"{{WRAPPER}} .grid-filter-wrap .filter-item.active":"color: {{VALUE}};"}},{"name":"filter_typography","label":"Filter Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .grid-filter-wrap .filter-item"}]},{"name":"section_style","label":"Title Style","tab":"style","controls":[{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-item--inner .wp-title":"color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-item--inner .wp-title"}]},{"name":"section_excerpt_style","label":"Excerpt Style","tab":"style","controls":[{"name":"exerpt_color","label":"Excerpt Color","type":"color","selectors":{"{{WRAPPER}} .pxl-item--inner .pxl--excerpt":"color: {{VALUE}};"}},{"name":"exerpt_typography","label":"Exerpt Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-item--inner .pxl--excerpt"}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'imagesloaded','isotope','pxl-post-grid' );
}